/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head';
import { Box } from '@chakra-ui/react';

export const Layout = ({ children }) => {
  return (
    <Box m="0" p="0">
      <Head>
        <title>Choco</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Quando&family=Roboto+Mono&display=swap" rel="stylesheet" />
      </Head>

      { children }
    </Box>
  );
}