/* eslint-disable @next/next/no-css-tags */
/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";

const HtmlHeadComponent = () => {
  return (
    <Head>
      <title>Choco</title>
      <meta name="description" content="Generated by create next app" />
      <link href="/dist/output.css" rel="stylesheet" />
    </Head>
  );
};

export default HtmlHeadComponent;
